<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ShutdownTimer</AssemblyName>
    <RootNamespace>ShutdownTimer</RootNamespace>
    <Version>0.3.0</Version>
    <Product>Shutdown Timer</Product>
    <Description>Таймер выключения ПК с уведомлениями и работой в трее</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShutdownTimer.Core\ShutdownTimer.Core.csproj" />
  </ItemGroup>

</Project>
